### ISSUE TITLE
[Advanced Blacklist] Add multiple users

### ISSUE THREAD

**Issue by Onii-Chan-Discord** [Just-Jojo/JojoCogs#60]
### Cog

AdvancedBlacklist

### Details

A new command to add multiple users at once to the blacklist

**Comment by Just-Jojo** [comment]
This cog already has this feature. Using `[p]blacklist add user1 user2 I don't like either of you` will blacklist both of those users

**Comment by Onii-Chan-Discord** [comment]
Hmm weird, for me it seems to add anything after the id as a reason, i might need to update my cog though.
