### ISSUE TITLE
[CycleStatus] Different types per status

### ISSUE THREAD

**Issue by CptDinosaur** [Just-Jojo/JojoCogs#76]
### Cog

Cyclestatus

### Details

Instead of having a single type, allow different added statuses to change the type of status

**Comment by Just-Jojo** [comment]
Hi there, CycleStatus has the `[p]cyclestatus type` command, which will allow you to change the status' type from the default `Playing` to any of the types stated in the help for the aforementioned command.

Unless I am misunderstanding in which case please provide a more detailed explanation as to what you're looking for

**Comment by CptDinosaur** [comment]
I would like to be able to choose a different type for each cycling status.

So every minute, it changes both type and status.

**Comment by CptDinosaur** [comment]
It would also be useful if the 1 minute delay was instead a config value which can be changed.

See the logic for this in the [rndstatus cog](https://github.com/aikaterna/aikaterna-cogs/blob/v3/rndstatus/rndstatus.py)

**Comment by Just-Jojo** [comment]
I see. I will consider adding the different activity modes for different statuses, however I will most likely not implement a setting for changing the cycle timer as the way I have it right now wouldn't really work with that and I don't feel like rewriting the system.

**Comment by Just-Jojo** [comment]
I will most likely not add this feature. Maybe at some point I will have the energy to do this but not atm
