### ISSUE TITLE
Package loading failed

### ISSUE THREAD

**Issue by ChrisiTV10** [Just-Jojo/JojoCogs#81]
### Cog

AdvancedLog

### Details

Failed to load the cog

### Discord User Information

ChrisiTV#0815

### Traceback details (if applicable)

```py
Exception during loading of package
Traceback (most recent call last):
  File "/home/pi/redenv/lib/python3.9/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/home/pi/redenv/lib/python3.9/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression
```

### Reproduction

i added the repo then installed advancedlog. After that i wanted to load the cog... Error

**Comment by Just-Jojo** [comment]
Hi there! What version of Red is your bot running? (You can check using `[p]info` with [p] being your bot's prefix)

If you are running Red 3.5.0 or later and added the main/master branch of the repo, I have not yet updated it for Red 3.5. You would need to install the cog from the dpy2 branch instead.

**Comment by ChrisiTV10** [comment]
im running on 3.5.1

okay thank you for the help!
